name = "floof-storefront"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
PUBLIC_MEDUSA_URL = "https://floof-backend-production-6742.up.railway.app"
PUBLIC_MEDUSA_PK = "pk_a027f332298303408a1c3e6ce0c4fae09cd0a33985c5bab22819be960cf1fca4"
PUBLIC_STRIPE_PK = ""
